version: "3.9"
services:
  minecraft:
    build: .
    restart: always
    container_name: "mcserver"
    environment:
      MEMORYSIZE: "16G"
      PAPERMC_FLAGS: ""
    volumes:
      - "./data:/data:rw"
    ports:
      - "25565:25565"
    stdin_open: true
    tty: true
