name: gronia
version: 0.1.1
main: org.gronia.plugin.Gronia
website: https://gronia.org
depend: [Citizens,GuiLib]

api-version: 1.19
commands:
  sack:
    description: Sack
    usage: /sack
  ptp:
    description: Perfect TP
    usage: /ptp
  uei:
    description: Dont execute this command
    usage: /uei dont
  storage:
    description: Storage
    usage: /storage
  repair:
    description: Repair
    usage: /repair <unsafe>
  griefing:
    description: Griefing
    usage: /griefing add|remove|list
  ge:
    description: GE
    usage: /ge
